const mongoose = require('mongoose');
const House = require('../models/house.model');
const dbConnection = require('../../database/connect');

const houses = [
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 500,
        rooms: 6,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 90,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 450,
        rooms: 6,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 500,
        rooms: 6,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 90,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 450,
        rooms: 6,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 500,
        rooms: 6,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 215,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 450,
        rooms: 6,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 190,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 500,
        rooms: 7,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 90,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 450,
        rooms: 6,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: false,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 300,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 500,
        rooms: 6,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 90,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 150,
        rooms: 2,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 295,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 500,
        rooms: 6,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 325,
        rooms: 4,
        bathrooms: 3,
        availability: false,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 450,
        rooms: 6,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 180,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 250,
        rooms: 4,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 90,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 250,
        rooms: 3,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: false,
    },
    {
        meters: 500,
        rooms: 6,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 160,
        rooms: 3,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 90,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 125,
        rooms: 3,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 90,
        rooms: 2,
        bathrooms: 1,
        availability: false,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 4,
        availability: true,
    },
    {
        meters: 200,
        rooms: 3,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 90,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 150,
        rooms: 3,
        bathrooms: 3,
        availability: false,
    },
    {
        meters: 120,
        rooms: 3,
        bathrooms: 2,
        availability: true,
    }, 
    {
        meters: 110,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 150,
        rooms: 4,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 95,
        rooms: 2,
        bathrooms: 2,
        availability: true,
    },
    {
        meters: 250,
        rooms: 4,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 500,
        rooms: 6,
        bathrooms: 3,
        availability: true,
    },
    {
        meters: 60,
        rooms: 2,
        bathrooms: 1,
        availability: true,
    },
    {
        meters: 160,
        rooms: 3,
        bathrooms: 3,
        availability: false,
    },
    {
        meters: 190,
        rooms: 4,
        bathrooms: 2,
        availability: false,
    },
    {
        meters: 350,
        rooms: 5,
        bathrooms: 3,
        availability: false,
    },
];

const housesDocuments = houses.map(house => new House(house));

mongoose.connect(dbConnection.MONGO_DB,   {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
    .then(async () => {
        const allHouses = await House.find();
        if (allHouses.length > 0) {
            await House.collection.drop();
        }
    })
    .catch((error) => console.error('Error eliminando colección houses:', error))
    .then(async () => {
        await House.insertMany(housesDocuments)
    })
    .catch((error) => console.error('Error al insertar en houses:', error))

    .finally(() => mongoose.disconnect());